// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scholarship_Distribution_Management_System.Models.Entities;

#nullable disable

namespace Scholarship_Distribution_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616093813_AddIsDuyetHoatDongToDonXinHocBong")]
    partial class AddIsDuyetHoatDongToDonXinHocBong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDLopSH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LopSHID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LopSHID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.Diem", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("DiemHocTap")
                        .HasColumnType("real");

                    b.Property<float?>("DiemRenLuyen")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("DiemHocTap")
                        .HasColumnType("real");

                    b.Property<float?>("DiemRenLuyen")
                        .HasColumnType("real");

                    b.Property<bool?>("DuyetCapPhatHocBong")
                        .HasColumnType("bit");

                    b.Property<bool?>("DuyetHoiDong")
                        .HasColumnType("bit");

                    b.Property<string>("IDDot")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("KQDiemHT")
                        .HasColumnType("real");

                    b.Property<float?>("KQDiemRL")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<bool>("isDuyetHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDDot");

                    b.HasIndex("IDSinhVien");

                    b.ToTable("DonXinHocBongs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.DotHocBong", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDauNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoiDongDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThucNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPTCDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("bigint");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("DotHocBongs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.HoatDong", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHoatDong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HoatDongs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.HoatDongCuaSinhVien", b =>
                {
                    b.Property<string>("IDDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDHoatDong")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDDon", "IDHoatDong");

                    b.HasIndex("IDHoatDong");

                    b.ToTable("HoatDongCuaSinhViens");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.KQHoatDong", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDHoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("IDDon");

                    b.HasIndex("IDHoatDong");

                    b.HasIndex("IDSinhVien");

                    b.ToTable("KqHoatDong");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.KQNghienCuu", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDNghienCuu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("IDDon");

                    b.HasIndex("IDNghienCuu");

                    b.HasIndex("IDSinhVien");

                    b.ToTable("KqNghienCuu");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.Khoa", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.LopSH", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLopSH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDNganh");

                    b.ToTable("LopSHs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.Nganh", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDKhoa");

                    b.ToTable("Nganhs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuCuaSinhVien", b =>
                {
                    b.Property<string>("IDDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDNghienCuu")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDDon", "IDNghienCuu");

                    b.HasIndex("IDNghienCuu");

                    b.ToTable("nghienCuuCuaSinhViens");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuKhoaHoc", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDeTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhTich")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NghienCuuKhoaHocs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.LopSH", "LopSH")
                        .WithMany()
                        .HasForeignKey("LopSHID");

                    b.Navigation("LopSH");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.Diem", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", "User")
                        .WithMany("DiemList")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.DotHocBong", "DotHocBong")
                        .WithMany()
                        .HasForeignKey("IDDot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", "SinhVien")
                        .WithMany()
                        .HasForeignKey("IDSinhVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DotHocBong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.DotHocBong", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.HoatDongCuaSinhVien", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", "DonXinHocBong")
                        .WithMany("HoatDongCuaSinhViens")
                        .HasForeignKey("IDDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.HoatDong", "HoatDong")
                        .WithMany("HoatDongCuaSinhViens")
                        .HasForeignKey("IDHoatDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonXinHocBong");

                    b.Navigation("HoatDong");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.KQHoatDong", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", "Don")
                        .WithMany()
                        .HasForeignKey("IDDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.HoatDong", "HoatDong")
                        .WithMany("KQHoatDongs")
                        .HasForeignKey("IDHoatDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", "SinhVien")
                        .WithMany()
                        .HasForeignKey("IDSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Don");

                    b.Navigation("HoatDong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.KQNghienCuu", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", "Don")
                        .WithMany()
                        .HasForeignKey("IDDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuKhoaHoc", "NghienCuu")
                        .WithMany("KqNghienCuus")
                        .HasForeignKey("IDNghienCuu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", "SinhVien")
                        .WithMany()
                        .HasForeignKey("IDSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Don");

                    b.Navigation("NghienCuu");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.LopSH", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.Nganh", "Nganh")
                        .WithMany()
                        .HasForeignKey("IDNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.Nganh", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("IDKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuCuaSinhVien", b =>
                {
                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", "DonXinHocBong")
                        .WithMany("NghienCuuCuaSinhViens")
                        .HasForeignKey("IDDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuKhoaHoc", "NghienCuu")
                        .WithMany("NghienCuuCuaSinhViens")
                        .HasForeignKey("IDNghienCuu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonXinHocBong");

                    b.Navigation("NghienCuu");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("DiemList");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.DonXinHocBong", b =>
                {
                    b.Navigation("HoatDongCuaSinhViens");

                    b.Navigation("NghienCuuCuaSinhViens");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.HoatDong", b =>
                {
                    b.Navigation("HoatDongCuaSinhViens");

                    b.Navigation("KQHoatDongs");
                });

            modelBuilder.Entity("Scholarship_Distribution_Management_System.Models.Entities.NghienCuuKhoaHoc", b =>
                {
                    b.Navigation("KqNghienCuus");

                    b.Navigation("NghienCuuCuaSinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
